name: Lint

on:
  push:
    branches: ['main']
  pull_request_target:
    branches: ['main']

permissions:
  checks: write
  contents: write

jobs:
  lint:
    name: Lint code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run linters
        uses: wearerequired/lint-action@v2
        with:
          auto_fix: true
          eslint: true
          eslint_extensions: js,jsx,ts,tsx
